### ISSUE TITLE
Login does not work on Firefox

### ISSUE THREAD

**Issue by friedger** [djnicholson/blockmarks#2]
I am using FireFox; when I click the signin button I see the following message in the console:

ReferenceError: chrome is not defined[Learn More] all.js:26:305131

    isRunningInPlugin https://clickbox.link/all.js:26 signIn https://clickbox.link/all.js:26 onclick https://clickbox.link/:1

**Comment by djnicholson** [comment]
Thanks for reporting this @friedger
